version: '3'
services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: